spring:
  datasource:
    url: ${db_url:jdbc:mysql://localhost:3306/seulahDms?createDatabaseIfNotExist=true}
    username: ${db_username:root}
    password: ${db_password:1124}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: SeulahApplication
server:
  port: 8085
logging:
  level:
    org:
      springframework:
        web: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

